In [19]:
import pandas as pd

data = pd.read_excel("data (2).xlsx")
df.loc [1:11:5,['Category','Product','Sales']]

     Category Product  Sales
1   Furniture   Chair   7000
6    Clothing   Jeans   4000
11  Furniture   Chair   8000

In [1]:
import pandas as pd

data = {'Name': ['Amit', 'Sunita', 'Raj'],
        'Sales': [12000, 15000, 18000]}

df = pd.DataFrame(data)

In [3]:
df.describe()

           OrderID                 Date         Sales        Profit   Quantity
count    15.000000                   15     15.000000     15.000000  15.000000
mean   1008.000000  2025-01-08 00:00:00  21766.666667   3680.000000   3.933333
min    1001.000000  2025-01-01 00:00:00   3000.000000    600.000000   1.000000
25%    1004.500000  2025-01-04 12:00:00   6500.000000   1200.000000   2.000000
50%    1008.000000  2025-01-08 00:00:00  14000.000000   2800.000000   3.000000
75%    1011.500000  2025-01-11 12:00:00  26000.000000   4750.000000   5.000000
max    1015.000000  2025-01-15 00:00:00  60000.000000  10000.000000  10.000000
std       4.472136                  NaN  19878.979087   3115.903905   2.520393

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   15 non-null     int64
 1   Date      15 non-null     datetime64[us]
 2   Region    15 non-null     str
 3   Category  15 non-null     str
 4   Product   15 non-null     str
 5   Sales     15 non-null     int64
 6   Profit    15 non-null     int64
 7   Quantity  15 non-null     int64
dtypes: datetime64[us](1), int64(4), str(3)
memory usage: 1.1 KB

In [11]:
df['Date'].value_counts()

Date
2025-01-01    1
2025-01-02    1
2025-01-03    1
2025-01-04    1
2025-01-05    1
2025-01-06    1
2025-01-07    1
2025-01-08    1
2025-01-09    1
2025-01-10    1
2025-01-11    1
2025-01-12    1
2025-01-13    1
2025-01-14    1
2025-01-15    1
Name: count, dtype: int64

In [12]:
df[['Date','OrderID']]

         Date  OrderID
0  2025-01-01     1001
1  2025-01-02     1002
2  2025-01-03     1003
3  2025-01-04     1004
4  2025-01-05     1005
5  2025-01-06     1006
6  2025-01-07     1007
7  2025-01-08     1008
8  2025-01-09     1009
9  2025-01-10     1010
10 2025-01-11     1011
11 2025-01-12     1012
12 2025-01-13     1013
13 2025-01-14     1014
14 2025-01-15     1015

In [13]:
# df = df.rename(columns={'OrderID':'ID'})
# df
# df.info()
df['Sales']=df['Sales'].astype('str')

In [14]:
df

    OrderID       Date Region     Category Product  Sales  Profit  Quantity
0      1001 2025-01-01  North  Electronics  Laptop  55000    8000         2
1      1002 2025-01-02  South    Furniture   Chair   7000    1200         5
2      1003 2025-01-03   East  Electronics  Mobile  25000    4000         3
3      1004 2025-01-04   West     Clothing   Shirt   3000     600        10
4      1005 2025-01-05  North    Furniture   Table  12000    2500         2
5      1006 2025-01-06  South  Electronics  Laptop  55000    9000         2
6      1007 2025-01-07   East     Clothing   Jeans   4000     700         6
7      1008 2025-01-08   West  Electronics  Mobile  27000    4500         4
8      1009 2025-01-09  North     Clothing  Jacket   6000    1200         3
9      1010 2025-01-10  South    Furniture    Sofa  25000    5000         1
10     1011 2025-01-11   East  Electronics  Laptop  60000   10000         2
11     1012 2025-01-12   West    Furniture   Chair   8000    1500         4
12     1013 2025-01-13  North  Electronics  Mobile  22000    3500         5
13     1014 2025-01-14  South     Clothing   Shirt   3500     700         8
14     1015 2025-01-15   East    Furniture   Table  14000    2800         2

In [15]:
import pandas as pd

data = pd.read_excel("data (2).xlsx")
df = pd.DataFrame(data)
print(df)

    OrderID       Date Region     Category Product  Sales  Profit  Quantity
0      1001 2025-01-01  North  Electronics  Laptop  55000    8000         2
1      1002 2025-01-02  South    Furniture   Chair   7000    1200         5
2      1003 2025-01-03   East  Electronics  Mobile  25000    4000         3
3      1004 2025-01-04   West     Clothing   Shirt   3000     600        10
4      1005 2025-01-05  North    Furniture   Table  12000    2500         2
5      1006 2025-01-06  South  Electronics  Laptop  55000    9000         2
6      1007 2025-01-07   East     Clothing   Jeans   4000     700         6
7      1008 2025-01-08   West  Electronics  Mobile  27000    4500         4
8      1009 2025-01-09  North     Clothing  Jacket   6000    1200         3
9      1010 2025-01-10  South    Furniture    Sofa  25000    5000         1
10     1011 2025-01-11   East  Electronics  Laptop  60000   10000         2
11     1012 2025-01-12   West    Furniture   Chair   8000    1500         4
12     1013 2025-01-13  North  Electronics  Mobile  22000    3500         5
13     1014 2025-01-14  South     Clothing   Shirt   3500     700         8
14     1015 2025-01-15   East    Furniture   Table  14000    2800         2